library(plyr)
Householdcolnames <- read.table("household_power_consumption.txt",sep = ';',header = TRUE,nrow =2)
Householdcon <- read.table("household_power_consumption.txt",sep = ';',skip=grep("1/2/2007",readLines("household_power_consumption.txt")),nrows = 2879)
names(Householdcon) <- names(Householdcolnames )
f <- strptime(paste(as.character(as.Date( as.character(Householdcon$Date),"%d/%m/%Y")),as.character(Householdcon$Time)), "%Y-%m-%d %H:%M:%S")
newhouseHold <- mutate(Householdcon,DateTime = f)
subMetering1 <- as.numeric(newhouseHold$Sub_metering_1) 
subMetering2 <- as.numeric(newhouseHold$Sub_metering_2) 
subMetering3 <- as.numeric(newhouseHold$Sub_metering_3) 
png("plot3.png", width=480, height=480)
plot(f, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(f, subMetering2, type="l", col="red") 
lines(f, subMetering3, type="l", col="blue") 
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue")) 
dev.off() 

